/** @jsxImportSource theme-ui */

import Head from 'next/head';
import AnimatedSection from './animated-section';
import Header from './header';
import Section from './section';

export default function ProjectContainer({
  title,
  year,
  team,
  body,
  role,
  sections,
  showMainMedia,
  mainMedia,
}) {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <article>
        <Header
          title={title}
          body={body}
          year={year}
          showMainMedia={showMainMedia}
          mainMedia={mainMedia}
          role={role}
        />
        <div
          className="content"
          sx={{
            pt: showMainMedia ? '106px' : '0px',
            pb: '106px',
          }}
        >
          {sections && (
            <div sx={{ position: 'relative', zIndex: 2 }}>
              {sections.map((section) =>
                section.layout.parallax ? (
                  <AnimatedSection key={section._key} {...section} />
                ) : (
                  <Section key={section._key} {...section} />
                )
              )}
            </div>
          )}
          <section
            sx={{ position: 'relative', variant: 'superGrid' }}
          >
            {team && (
              <div sx={{ gridColumn: '2/14' }}>
                <h2 sx={{ variant: 'text.sectionTitle' }}>credits</h2>
                {team.map((m) => (
                  <div key={m._key} sx={{ display: 'flex' }}>
                    <h3 sx={{ fontFamily: 'heading', fontSize: 1 }}>
                      {m.name}
                    </h3>
                    : {m.role}
                  </div>
                ))}
              </div>
            )}
          </section>
        </div>
      </article>
    </>
  );
}
