/** @jsxImportSource theme-ui */
import Head from 'next/head';
import { getClient } from '@lib/sanity.server';

import ProjectContainer from '@components/project';
import { otherProjects, projectQuery } from '@lib/queries';
import TransitionLayout from '@components/TransitionLayout';

const Project = ({ data }) => {
  if (!data || !data.project) return null;
  const { title } = data.project;

  return (
    <TransitionLayout>
      <Head>
        <title>{title}</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ProjectContainer data={data} />
    </TransitionLayout>
  );
};

export default Project;

export async function getStaticPaths() {
  const paths = await getClient().fetch(
    `*[_type == 'project' && defined(slug)][].slug.current`
  );
  return {
    paths: paths.map((slug) => ({
      params: {
        slug,
      },
    })),
    fallback: true,
  };
}

export async function getStaticProps({ params }) {
  const data = await getClient().fetch(
    `{
      "project": ${projectQuery},
      "navData": {
        ${otherProjects}
      }
    }
  `,
    {
      slug: params.slug,
    }
  );
  return {
    props: {
      data,
    },
  };
}
