import Head from 'next/head';
import {getClient} from './lib/sanity.server';

export default function Home({data}) {
  console.log(data);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <header></header>
      <main></main>
      <footer></footer>
    </div>
  );
}

export async function getStaticProps() {
  const allPostsQuery = `
    *[_type == "quickpost"] {
      ...,
      tags[]->
    }
  `;
  const data = await getClient().fetch(allPostsQuery);
  return {
    props: {
      data,
    },
  };
}
