import Head from 'next/head';
import {PortableText} from '@portabletext/react';
import {getClient} from '@lib/sanity.server';

export default function Home({data}) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        {data &&
          data.map(({_id, date, body, title}) => (
            <div key={_id}>
              <h2>{title}</h2>
              {date && <time dateTime={date}>{date}</time>}
              {body && <div>{body}</div>}
            </div>
          ))}
      </main>
      <footer></footer>
    </div>
  );
}

export async function getStaticProps() {
  const allPostsQuery = `
    *[_type in ["quickPost", 'post']] | order(publishedAt asc) {
      ...,
      tags[]->
    }
  `;
  const data = await getClient().fetch(allPostsQuery);
  return {
    props: {
      data,
    },
  };
}
